---
- hosts: carefulsquid
  remote_user: root
  tasks:

  - name: install squid
    yum:
      name: squid
      state: latest
  
  - name: make dump directory
    shell: mkdir /var/spool/squid

  - name: deploy squid config
    template: src=/srv/squid.conf dest=/etc/squid/squid.conf
    
  - name: deploy squid whitelist
    template: src=/srv/whitelist.txt dest=/etc/whitelist.txt

  - name: enable squid
    service:
      name: squid
      enabled: yes

  - name: restart squid
    service:
      name: squid
      state: restarted

